  
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-worker
  labels:
    jenkins: jenkins-worker
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["tail", "-f", "/dev/null"] 
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
